artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/datasets/shayanfazeli/heartbeat
  ptbdb_normal_data_path: data/ptbdb_normal.csv
  ptbdb_abnormal_data_path: data/ptbdb_abnormal.csv

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.keras
  

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.keras